import { failure, isObjectId, success } from "@/lib/api";
import { requireAuth } from "@/lib/auth";
import { connectDB } from "@/lib/mongodb";
import RequestModel from "@/lib/models/Request";
import Notification from "@/lib/models/Notification";
import Answer from "@/lib/models/Answer";
import Bookmark from "@/lib/models/Bookmark";
import User from "@/lib/models/User";
const statuses = ["open", "resolved", "closed"];
export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) { const { id } = await params; if (!isObjectId(id)) return failure("Invalid request id"); await connectDB(); const item = await RequestModel.findById(id).populate("author", "name department year points").lean(); return item ? success(item) : failure("Request not found", 404); }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const user = await requireAuth(); const { id } = await params; if (!user) return failure("Not authenticated", 401); if (!isObjectId(id)) return failure("Invalid request id"); await connectDB(); const item = await RequestModel.findById(id); if (!item) return failure("Request not found", 404); if (String(item.author) !== String(user._id) && user.role !== "admin") return failure("Not allowed", 403); const body = await request.json(); const allowed: Record<string, unknown> = {}; if (typeof body.title === "string" && body.title.trim().length >= 3 && body.title.trim().length <= 140) allowed.title = body.title.trim(); if (typeof body.description === "string" && body.description.trim().length >= 10 && body.description.trim().length <= 5000) allowed.description = body.description.trim(); if (typeof body.category === "string" && body.category.trim() && body.category.trim().length <= 60) allowed.category = body.category.trim(); if (body.status !== undefined) { if (!statuses.includes(body.status)) return failure("Invalid status"); allowed.status = body.status; } if (body.tags !== undefined && Array.isArray(body.tags)) allowed.tags = body.tags.filter((tag: unknown) => typeof tag === "string").map((tag: string) => tag.trim()).filter(Boolean).slice(0, 10); if (body.deadline !== undefined) { const date = body.deadline ? new Date(body.deadline) : null; if (date && Number.isNaN(date.getTime())) return failure("Invalid deadline"); allowed.deadline = date; } const statusChanged = allowed.status !== undefined && allowed.status !== item.status; Object.assign(item, allowed); await item.save(); if (statusChanged && String(item.author) !== String(user._id)) await Notification.create({ recipient: item.author, type: "status", title: "Request status updated", message: `Your request is now ${item.status}.`, request: item._id }); return success(await item.populate("author", "name department year points"), "Request updated"); } catch { return failure("Unable to update request", 500); } }
export async function DELETE(_: Request, { params }: { params: Promise<{ id: string }> }) { try { const user = await requireAuth(); const { id } = await params; if (!user) return failure("Not authenticated", 401); if (!isObjectId(id)) return failure("Invalid request id"); await connectDB(); const item = await RequestModel.findById(id); if (!item) return failure("Request not found", 404); if (String(item.author) !== String(user._id) && user.role !== "admin") return failure("Not allowed", 403); const answers = await Answer.find({ request: item._id }).select("author accepted"); for (const answer of answers) await User.findByIdAndUpdate(answer.author, { $inc: { answersGiven: -1, points: answer.accepted ? -65 : -10, acceptedAnswers: answer.accepted ? -1 : 0 } }); await Answer.deleteMany({ request: item._id }); await Bookmark.deleteMany({ request: item._id }); await Notification.deleteMany({ request: item._id }); await User.findByIdAndUpdate(item.author, { $inc: { questionsAsked: -1 } }); await item.deleteOne(); return success(null, "Request deleted"); } catch { return failure("Unable to delete request", 500); } }
