import { failure, isObjectId, success } from "@/lib/api";
import { requireAuth } from "@/lib/auth";
import { connectDB } from "@/lib/mongodb";
import Answer from "@/lib/models/Answer";
import Notification from "@/lib/models/Notification";
import RequestModel from "@/lib/models/Request";
import User from "@/lib/models/User";
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const user = await requireAuth(); const { id } = await params; if (!user) return failure("Not authenticated", 401); if (!isObjectId(id)) return failure("Invalid answer id"); await connectDB(); const answer = await Answer.findById(id); if (!answer) return failure("Answer not found", 404); const body = await request.json(); if (typeof body.content === "string") { if (String(answer.author) !== String(user._id) && user.role !== "admin") return failure("Not allowed", 403); if (body.content.trim().length < 2 || body.content.trim().length > 5000) return failure("Invalid answer"); answer.content = body.content.trim(); await answer.save(); return success(await answer.populate("author", "name department year points"), "Answer updated"); }
    if (body.accepted === true || body.helpful === true) { const helpRequest = await RequestModel.findById(answer.request); if (!helpRequest) return failure("Request not found", 404); if (String(helpRequest.author) !== String(user._id) && user.role !== "admin") return failure("Only the request owner can mark answers", 403); if (answer.accepted) return success(await answer.populate("author", "name department year points"), "Answer already accepted"); const claimedRequest = await RequestModel.findOneAndUpdate({ _id: helpRequest._id, acceptedAnswer: null }, { acceptedAnswer: answer._id, status: "resolved" }, { new: true }); if (!claimedRequest) return failure("An answer has already been accepted", 409); await Answer.updateMany({ request: answer.request }, { accepted: false }); answer.accepted = true; answer.helpful = true; await answer.save(); await User.findByIdAndUpdate(answer.author, { $inc: { points: 55, acceptedAnswers: 1 } }); if (String(answer.author) !== String(user._id)) await Notification.create({ recipient: answer.author, type: "accepted", title: "Answer accepted", message: "Your answer was marked accepted and helpful.", request: claimedRequest._id, answer: answer._id }); return success(await answer.populate("author", "name department year points"), "Answer marked accepted"); }
    return failure("No supported changes supplied");
  } catch { return failure("Unable to update answer", 500); } }
export async function DELETE(_: Request, { params }: { params: Promise<{ id: string }> }) { try { const user = await requireAuth(); const { id } = await params; if (!user) return failure("Not authenticated", 401); if (!isObjectId(id)) return failure("Invalid answer id"); await connectDB(); const answer = await Answer.findById(id); if (!answer) return failure("Answer not found", 404); if (String(answer.author) !== String(user._id) && user.role !== "admin") return failure("Not allowed", 403); await answer.deleteOne(); await RequestModel.findByIdAndUpdate(answer.request, answer.accepted ? { $inc: { answerCount: -1 }, $set: { acceptedAnswer: null, status: "open" } } : { $inc: { answerCount: -1 } }); await User.findByIdAndUpdate(answer.author, { $inc: { answersGiven: -1, points: answer.accepted ? -65 : -10, acceptedAnswers: answer.accepted ? -1 : 0 } }); return success(null, "Answer deleted"); } catch { return failure("Unable to delete answer", 500); } }
